// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "C:__Users__Administrator__Desktop__组件库__Aa-ui-React__node_modules__dumi__dist__client__pages__404" */'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/src/alert/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "C:__Users__Administrator__Desktop__组件库__Aa-ui-React__node_modules__dumi__dist__client__pages__Demo__index" */'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
