// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/Administrator/Desktop/组件库/Aa-ui-React/node_modules/dumi/theme-default/slots/SearchResult/index.js';
